// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXQEf5PcpmtxG6ZZb7AQ86FmVRy4HjlKU',
    appId: '1:1031606273563:web:64005b39a715ff04831abe',
    messagingSenderId: '1031606273563',
    projectId: 'learnflutter-731df',
    authDomain: 'learnflutter-731df.firebaseapp.com',
    databaseURL: 'https://learnflutter-731df-default-rtdb.firebaseio.com',
    storageBucket: 'learnflutter-731df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-psSLVuea8W4IVZtj_ucp6YOHrel0IEI',
    appId: '1:1031606273563:android:a6d8c00c2541e40f831abe',
    messagingSenderId: '1031606273563',
    projectId: 'learnflutter-731df',
    databaseURL: 'https://learnflutter-731df-default-rtdb.firebaseio.com',
    storageBucket: 'learnflutter-731df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBar8AZO9NzU7ke3yQMthJyWdYJpQcSGtA',
    appId: '1:1031606273563:ios:6bb7aa677f806cef831abe',
    messagingSenderId: '1031606273563',
    projectId: 'learnflutter-731df',
    databaseURL: 'https://learnflutter-731df-default-rtdb.firebaseio.com',
    storageBucket: 'learnflutter-731df.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBar8AZO9NzU7ke3yQMthJyWdYJpQcSGtA',
    appId: '1:1031606273563:ios:6bb7aa677f806cef831abe',
    messagingSenderId: '1031606273563',
    projectId: 'learnflutter-731df',
    databaseURL: 'https://learnflutter-731df-default-rtdb.firebaseio.com',
    storageBucket: 'learnflutter-731df.firebasestorage.app',
    iosBundleId: 'com.example.learnFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXQEf5PcpmtxG6ZZb7AQ86FmVRy4HjlKU',
    appId: '1:1031606273563:web:f9a8e870fdb1ead6831abe',
    messagingSenderId: '1031606273563',
    projectId: 'learnflutter-731df',
    authDomain: 'learnflutter-731df.firebaseapp.com',
    databaseURL: 'https://learnflutter-731df-default-rtdb.firebaseio.com',
    storageBucket: 'learnflutter-731df.firebasestorage.app',
  );
}
